### ISSUE TITLE
Disable Local and Remote Control missing from LZW-30 SN

### ISSUE THREAD

**Issue by bgorczyk** [InovelliUSA/SmartThingsEdgeInovelli#3]
No menu options for DLC or DRC.

**Comment by InovelliUSA** [comment]
These should both exist as capabilities though, right? So they can be set with automations? 

Local control is actually a selectable option in the device page, but I left remote control off. This was because I figured a lot of people would probably get confused by it and not use it anyway. I'm wondering if they need to be in both places?

![image](https://user-images.githubusercontent.com/37669481/210015016-1f885157-491f-4dee-aed7-42d1599c1bbd.png)

![image](https://user-images.githubusercontent.com/37669481/210015060-61b168ae-b59a-48a5-b271-f8a99172ff01.png)

![image](https://user-images.githubusercontent.com/37669481/210015097-4b7ca728-cd37-4a39-91e2-ac809c63c5fb.png)

![image](https://user-images.githubusercontent.com/37669481/210015121-78ae300a-9b2b-4586-8447-38e19179db6c.png)

**Comment by bgorczyk** [comment]
Ugh, I totally missed the Local Control on the Device Page!  Muscle memory had me going into settings.

I understand the logic on the Remote Control.  I actually never use that, so as long as it's accessible via a Routine, I think that's fine.

False alarm, but thanks for looking!

Bry
